---
title: "p8105_hw5_am4656"
author: "Aaron Mittel"
date: "2022-11-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

(THIS IS JUST A SAVED SPACE FOR PROBLEM 3. DELETE IN FUTURE COMMITS. KEPT HERE TO ALLOW EFFECTIVING KNITTING OF THE PRIMARY RMD HOWEWORK SUBMISSION)

# Problem 3
```{r mu = 0, include = TRUE, message = FALSE, echo = FALSE}
mean_ttest = function(n = 30, mu = 0, sigma = 5) {  
  prob3_data = tibble(
    x = rnorm(n, mean = mu, sd = sigma),
    )
  
  prob3_data %>% 
    summarize(
      mu_sample = mean(x)
    )
}
  
  t_test = t.test(x, alternative = "two.sided", mu = 0, paired = FALSE, alpha = 0.05) %>%
        broom::tidy()
  
prob3_df_mean0 = 
  expand_grid(
    mu = 0,
    iter = 1:5000
  ) %>% 
  mutate(
    estimate_df = map(mu, mean_ttest)) %>% 
  unnest(estimate_df)
```

```{r, mu varies from 0 - 6, include = TRUE, message = FALSE, echo = FALSE}
prob3_df = 
  expand_grid(
    sample_size = 30,
    mean = c(0,1,2,3,4,5,6),
    iter = 1:5000
  ) %>% 
  mutate(
    estimate_df = map(mean, mean_ttest)) %>% 
  unnest(estimate_df)


prob3_df %>% 
  mutate(
    significant = if_else(t_test$p.value < 0.05, TRUE, FALSE)
  ) %>% 
  group_by(mean, significant) %>% 
  summarize(
    n = n())
```

y-axis should be power, which is = 1 - beta. Beta is the chance of making a type II error (i.e. false negative rate). Thus, y-axis should be the proportion of 

```{r}
sim_results_test = 
  expand_grid(
    mu = c(6),
    iter = 1:5000
  ) %>% 
  mutate(
    estimate_df = map(mu, sim_mean_sd)
  ) %>% 
  unnest(estimate_df)
```

